In [68]:
import pandas as pd
import numpy as np
data  = pd.DataFrame.from_csv('data/ncaa-team-data.csv')
data

,Team,Seed,Year,Efficiency Margin,Offensive Efficiency,Defensive Efficiency,Tempo,Luck,Strength of Schedule,Opponent Offense,Opponent Defense,Non-Conference Strength of Schedule
0,Gonzaga,1,2017,32.05,118.4,86.3,70.1,0.020,2.99,106.2,103.2,1.02
1,Villanova,1,2017,29.88,122.4,92.5,64.0,0.010,9.33,109.8,100.4,3.55
2,North Carolina,1,2017,28.22,120.7,92.5,71.2,0.037,12.49,112.0,99.5,3.87
3,Kentucky,2,2017,27.72,119.1,91.4,71.9,0.006,10.98,110.4,99.5,3.74
4,Florida,4,2017,27.50,116.9,89.4,68.9,-0.041,12.46,110.2,97.7,8.19
5,Kansas,1,2017,27.45,122.0,94.5,70.2,0.067,12.43,111.2,98.7,2.39
6,West Virginia,4,2017,27.17,116.5,89.4,69.9,-0.043,10.84,110.0,99.2,-7.97
7,Wichita St.,10,2017,26.14,118.7,92.6,67.9,-0.021,1.50,105.0,103.5,-0.32
8,Louisville,2,2017,25.51,117.2,91.7,67.9,-0.023,11.14,111.6,100.4,4.20
9,Oregon,3,2017,25.02,118.2,93.2,67.0,0.034,8.05,109.2,101.1,0.51
10,SMU,6,2017,24.74,119.8,95.0,63.4,0.003,3.25,105.3,102.0,-0.92
11,Virginia,5,2017,24.29,112.2,87.9,59.1,-0.030,11.68,111.4,99.7,2.29
12,Baylor,3,2017,24.23,117.1,92.9,63.6,0.023,13.08,111.6,98.5,1.67
13,Duke,2,2017,24.17,121.0,96.9,68.2,0.014,11.43,111.0,99.5,0.03
14,Saint Mary's,7,2017,23.66,118.7,95.0,60.2,0.030,0.42,104.3,103.9,-4.12
15,UCLA,3,2017,23.63,124.0,100.4,72.5,0.021,5.18,107.9,102.7,-4.66
16,Iowa St.,5,2017,23.45,119.7,96.3,68.3,-0.019,14.05,112.6,98.5,-0.74
17,Arizona,2,2017,23.31,118.4,95.1,66.0,0.046,7.13,108.6,101.5,1.69
18,Purdue,4,2017,23.12,116.9,93.8,69.1,0.016,9.00,109.6,100.6,-2.37
19,Michigan,7,2017,23.05,122.3,99.3,63.0,-0.025,10.76,110.3,99.5,-0.53
20,Wisconsin,8,2017,22.99,115.1,92.1,63.4,-0.003,10.00,110.5,100.5,-1.29
21,Oklahoma St.,10,2017,22.47,126.0,103.5,70.3,-0.071,14.42,112.0,97.5,3.07
22,Cincinnati,6,2017,22.18,115.0,92.8,63.5,0.026,4.17,107.1,102.9,-0.47
23,South Carolina,7,2017,20.81,108.9,88.1,68.6,-0.005,10.63,110.1,99.5,1.93
24,Butler,4,2017,20.76,117.7,97.0,65.8,0.002,10.81,110.8,99.9,5.13
25,Florida St.,3,2017,20.06,115.5,95.4,71.2,0.039,8.82,110.6,101.8,-3.95
26,Notre Dame,5,2017,19.74,118.1,98.4,67.0,0.024,10.24,110.0,99.8,-3.84
27,Creighton,6,2017,18.83,115.3,96.5,71.1,0.004,8.97,110.2,101.3,-1.23
28,Kansas St.,11,2017,17.44,113.0,95.6,66.2,-0.029,11.56,110.6,99.0,-5.30
29,Xavier,11,2017,16.70,115.8,99.1,67.1,0.044,11.73,111.2,99.5,5.32
...,...,...,...,...,...,...,...,...,...,...,...,...
35,Charlotte,9,2002,15.72,112.1,96.4,68.4,-0.007,9.36,105.9,96.5,7.26
36,Tulsa,12,2002,15.59,114.0,98.4,71.0,0.001,2.52,102.4,99.8,-1.51
37,Western Kentucky,9,2002,14.50,108.3,93.8,69.0,0.060,-0.02,101.4,101.4,-0.41
38,Utah,12,2002,14.11,109.4,95.2,63.6,0.011,5.87,104.9,99.0,3.57
39,Valparaiso,13,2002,13.66,109.2,95.6,70.4,-0.031,-1.81,101.3,103.1,1.57
40,Southern Illinois,11,2002,13.46,107.1,93.6,71.5,0.035,1.64,103.4,101.8,1.98
41,Wisconsin,8,2002,13.25,108.6,95.3,64.8,0.049,10.36,107.3,97.0,8.01
42,Hawaii,10,2002,13.12,108.1,95.0,67.6,0.007,0.66,102.0,101.3,-4.81
43,Penn,11,2002,12.18,108.1,95.9,66.8,-0.018,-1.81,100.7,102.5,2.30
44,Creighton,12,2002,11.82,109.3,97.5,68.5,0.029,1.64,103.4,101.8,2.39
45,Pepperdine,10,2002,11.70,108.9,97.2,74.0,0.062,3.43,103.8,100.4,10.14
46,UNC Wilmington,13,2002,11.37,105.4,94.0,65.3,-0.002,0.52,101.5,101.0,3.85
47,Wyoming,11,2002,11.02,105.7,94.6,69.5,0.032,3.59,104.0,100.5,-4.39
48,Boston College,11,2002,9.95,107.2,97.3,70.3,0.040,7.14,104.1,97.0,-0.35
49,San Diego St.,13,2002,9.32,104.8,95.5,71.4,0.055,5.60,105.2,99.6,1.44
50,St. John's,9,2002,9.03,100.6,91.6,70.9,0.089,7.23,105.4,98.1,0.89
51,UC Santa Barbara,14,2002,8.90,106.1,97.2,64.8,-0.058,0.23,101.4,101.2,2.86
52,McNeese St.,14,2002,5.38,101.1,95.7,68.3,0.023,-5.14,97.8,102.9,7.24
53,Hampton,15,2002,3.99,107.8,103.8,70.4,0.014,-9.67,96.3,105.9,-1.90
54,Illinois Chicago,15,2002,3.88,106.9,103.0,69.2,0.040,1.50,102.3,100.8,-0.14
55,Davidson,13,2002,3.66,99.4,95.7,67.5,0.143,1.14,102.4,101.3,6.33
56,Murray St.,14,2002,1.37,104.7,103.4,71.0,0.018,-1.76,101.6,103.4,3.54
57,Central Connecticut,14,2002,0.90,98.5,97.6,66.2,0.138,-11.29,96.2,107.5,-3.19
58,Holy Cross,16,2002,-0.30,96.0,96.3,64.3,-0.048,-6.54,97.9,104.4,-3.17
59,Siena,16,2002,-1.20,98.6,99.8,68.9,-0.070,-3.90,98.7,102.6,-1.15
60,Florida Atlantic,15,2002,-2.48,97.5,100.0,71.6,0.061,-5.12,100.3,105.4,-5.36
61,Boston University,16,2002,-2.79,99.1,101.9,65.9,0.102,-9.64,95.7,105.3,-2.35
62,Montana,15,2002,-4.49,100.3,104.8,70.4,0.053,-2.12,101.6,103.7,0.67
63,Winthrop,16,2002,-5.33,95.2,100.5,68.0,0.039,-10.81,95.4,106.2,-1.40
64,Alcorn St.,16,2002,-8.69,98.1,106.8,74.2,0.097,-15.24,93.2,108.4,-2.29

In [7]:
ID = pd.read_csv('ncaa-team-id.csv')
ID.head()

   Team_ID         Team
0     1101  Abilene Chr
1     1102    Air Force
2     1103        Akron
3     1104      Alabama
4     1105  Alabama A&M

In [13]:
ID_teams = ID['Team']
for team in ID_teams:
    print team

Abilene Chr
Air Force
Akron
Alabama
Alabama A&M
Alabama St
Albany NY
Alcorn St
Alliant Intl
American Univ
Appalachian St
Arizona
Arizona St
Ark Little Rock
Ark Pine Bluff
Arkansas
Arkansas St
Armstrong St
Army
Auburn
Augusta
Austin Peay
Ball St
Baylor
Belmont
Bethune-Cookman
Binghamton
Birmingham So
Boise St
Boston College
Boston Univ
Bowling Green
Bradley
Brooklyn
Brown
Bryant
Bucknell
Buffalo
Butler
BYU
C Michigan
Cal Poly SLO
California
Campbell
Canisius
Cent Arkansas
Centenary
Central Conn
Charleston So
Charlotte
Chattanooga
Chicago St
Cincinnati
Citadel
Clemson
Cleveland St
Coastal Car
Col Charleston
Colgate
Colorado
Colorado St
Columbia
Connecticut
Coppin St
Cornell
Creighton
CS Bakersfield
CS Fullerton
CS Northridge
CS Sacramento
Dartmouth
Davidson
Dayton
Delaware
Delaware St
Denver
DePaul
Detroit
Drake
Drexel
Duke
Duquesne
E Illinois
E Kentucky
E Michigan
E Washington
East Carolina
Edwardsville
Elon
ETSU
Evansville
F Dickinson
Fairfield
FL Atlantic
FL Gulf Coast
Florida
Florida A&M
Florida Intl
Florida St
Fordham
Fresno St
Furman
G Washington
Ga Southern
Gardner Webb
George Mason
Georgetown
Georgia
Georgia St
Georgia Tech
Gonzaga
Grambling
Grand Canyon
Hampton
Hardin-Simmons
Hartford
Harvard
Hawaii
High Point
Hofstra
Holy Cross
Houston
Houston Bap
Howard
Idaho
Idaho St
IL Chicago
Illinois
Illinois St
Incarnate Word
Indiana
Indiana St
Iona
Iowa
Iowa St
IPFW
IUPUI
Jackson St
Jacksonville
Jacksonville St
James Madison
Kansas
Kansas St
Kennesaw
Kent
Kentucky
La Salle
Lafayette
Lamar
Lehigh
Liberty
Lipscomb
Long Beach St
Long Island
Longwood
Louisiana Tech
Louisville
Loy Marymount
Loyola MD
Loyola-Chicago
LSU
MA Lowell
Maine
Manhattan
Marist
Marquette
Marshall
Maryland
Massachusetts
McNeese St
MD E Shore
Memphis
Mercer
Miami FL
Miami OH
Michigan
Michigan St
Minnesota
Mississippi
Mississippi St
Missouri
Missouri KC
Missouri St
Monmouth NJ
Montana
Montana St
Morehead St
Morgan St
Morris Brown
MS Valley St
Mt St Mary's
MTSU
Murray St
N Colorado
N Dakota St
N Illinois
N Kentucky
Navy
NC A&T
NC Central
NC State
NE Illinois
NE Omaha
Nebraska
Nevada
New Hampshire
New Mexico
New Mexico St
New Orleans
Niagara
Nicholls St
NJIT
Norfolk St
North Carolina
North Dakota
North Florida
North Texas
Northeastern
Northern Arizona
Northern Iowa
Northwestern
Northwestern LA
Notre Dame
Oakland
Ohio
Ohio St
Okla City
Oklahoma
Oklahoma St
Old Dominion
Oral Roberts
Oregon
Oregon St
Pacific
Penn
Penn St
Pepperdine
Pittsburgh
Portland
Portland St
Prairie View
Presbyterian
Princeton
Providence
Purdue
Quinnipiac
Radford
Rhode Island
Rice
Richmond
Rider
Robert Morris
Rutgers
S Carolina St
S Dakota St
S Illinois
Sacred Heart
Sam Houston St
Samford
San Diego
San Diego St
San Francisco
San Jose St
Santa Barbara
Santa Clara
Savannah St
SC Upstate
SE Louisiana
SE Missouri St
Seattle
Seton Hall
SF Austin
Siena
SMU
South Alabama
South Carolina
South Dakota
South Florida
Southern Miss
Southern Univ
Southern Utah
St Bonaventure
St Francis NY
St Francis PA
St John's
St Joseph's PA
St Louis
St Mary's CA
St Peter's
Stanford
Stetson
Stony Brook
Syracuse
TAM C. Christi
TCU
Temple
Tennessee
Tennessee St
Tennessee Tech
Texas
Texas A&M
Texas St
Texas Tech
TN Martin
Toledo
Towson
Troy
Tulane
Tulsa
UTRGV
TX Southern
UAB
UC Davis
UC Irvine
UC Riverside
UCF
UCLA
ULL
ULM
UMBC
UNC Asheville
UNC Greensboro
UNC Wilmington
UNLV
USC
UT Arlington
UT San Antonio
Utah
Utah St
Utah Valley
UTEP
Utica
VA Commonwealth
Valparaiso
Vanderbilt
Vermont
Villanova
Virginia
Virginia Tech
VMI
W Carolina
W Illinois
WKU
W Michigan
W Salem St
W Texas A&M
Wagner
Wake Forest
Washington
Washington St
Weber St
West Virginia
WI Green Bay
WI Milwaukee
Wichita St
William & Mary
Winthrop
Wisconsin
Wofford
Wright St
Wyoming
Xavier
Yale
Youngstown St

In [14]:
ID['Team'] = ID['Team'].replace("Wichita St","Wichita St.")
ID['Team'] = ID['Team'].replace("St Mary's CA","Saint Mary's")
ID['Team'] = ID['Team'].replace("Iowa St","Iowa St.")
ID['Team'] = ID['Team'].replace("Oklahoma St","Oklahoma St.")
ID['Team'] = ID['Team'].replace("Florida St","Florida St.")
ID['Team'] = ID['Team'].replace("Kansas St","Kansas St.")
ID['Team'] = ID['Team'].replace("Michigan St","Michigan St.")
ID['Team'] = ID['Team'].replace("MTSU","Middle Tennessee")
ID['Team'] = ID['Team'].replace("VA Commonwealth","VCU")
ID['Team'] = ID['Team'].replace("ETSU","East Tennessee St.")
ID['Team'] = ID['Team'].replace("New Mexico St","New Mexico St.")
ID['Team'] = ID['Team'].replace("FL Gulf Coast","Florida Gulf Coast")
ID['Team'] = ID['Team'].replace("N Kentucky","Northern Kentucky")
ID['Team'] = ID['Team'].replace("Kent","Kent St.")
ID['Team'] = ID['Team'].replace("Jacksonville St","Jacksonville St.")
ID['Team'] = ID['Team'].replace("NC Central","North Carolina Central")
ID['Team'] = ID['Team'].replace("S Dakota St.","South Dakota St.")
ID['Team'] = ID['Team'].replace("Mt St Mary's","Mount St. Mary's")
ID['Team'] = ID['Team'].replace("TX Southern","Texas Southern")
ID['Team'] = ID['Team'].replace("Texas A&M","Texas A&M;")
ID['Team'] = ID['Team'].replace("SF Austin","Stephen F. Austin")
ID['Team'] = ID['Team'].replace("St Joseph's PA","Saint Joseph's")
ID['Team'] = ID['Team'].replace("Ark Little Rock","Arkansas Little Rock")
ID['Team'] = ID['Team'].replace("Oregon St","Oregon St.")
ID['Team'] = ID['Team'].replace("Fresno St","Fresno St.")
ID['Team'] = ID['Team'].replace("CS Bakersfield","Cal St. Bakersfield")
ID['Team'] = ID['Team'].replace("WI Green Bay","Green Bay")
ID['Team'] = ID['Team'].replace("Weber St","Weber St.")
ID['Team'] = ID['Team'].replace("Southern Univ","Southern")
ID['Team'] = ID['Team'].replace("F Dickinson","Fairleigh Dickinson")
ID['Team'] = ID['Team'].replace("San Diego St","San Diego St.")
ID['Team'] = ID['Team'].replace("NC State","North Carolina St.")
ID['Team'] = ID['Team'].replace("Boise St","Boise St.")
ID['Team'] = ID['Team'].replace("Georgia St","Georgia St.")
ID['Team'] = ID['Team'].replace("St John's","St. John's")
ID['Team'] = ID['Team'].replace("Albany NY","Albany")
ID['Team'] = ID['Team'].replace("E Washington","Eastern Washington")
ID['Team'] = ID['Team'].replace("Coastal Car","Costal Carolina")
ID['Team'] = ID['Team'].replace("North Dakota St","North Dakota St.")
ID['Team'] = ID['Team'].replace("Ohio St","Ohio St.")
ID['Team'] = ID['Team'].replace("St Louis","Saint Louis")
ID['Team'] = ID['Team'].replace("Arizona St","Arizona St.")
ID['Team'] = ID['Team'].replace("G Washington","George Washington")
ID['Team'] = ID['Team'].replace("Lafayette","Louisiana Lafayette")
ID['Team'] = ID['Team'].replace("American Univ","American")
ID['Team'] = ID['Team'].replace("E Kentucky","Eastern Kentucky")
ID['Team'] = ID['Team'].replace("W Michigan","Western Michigan")
ID['Team'] = ID['Team'].replace("WI Milwaukee","Milwaukee")
ID['Team'] = ID['Team'].replace("Cal Poly SLO","Cal Poly")
ID['Team'] = ID['Team'].replace("WI Milwaukee","Milwaukee")
ID['Team'] = ID['Team'].replace("Colorado St","Colorado St.")
ID['Team'] = ID['Team'].replace("Northwestern LA","Northwestern St.")
ID['Team'] = ID['Team'].replace("W Kentucky","Western Kentucky")
ID['Team'] = ID['Team'].replace("Brooklyn","LIU Brooklyn")
ID['Team'] = ID['Team'].replace("NC A&T","North Carolina A&T;")
ID['Team'] = ID['Team'].replace("Murray St","Murray St.")
ID['Team'] = ID['Team'].replace("Long Beach St","Long Beach St.")
ID['Team'] = ID['Team'].replace("Norfolk St","Norfolk St.")
ID['Team'] = ID['Team'].replace("MS Valley St","Mississippi Valley St.")
ID['Team'] = ID['Team'].replace("Utah St","Utah St.")
ID['Team'] = ID['Team'].replace("Morehead St","Morehead St.")
ID['Team'] = ID['Team'].replace("Indiana St","Indiana St.")
ID['Team'] = ID['Team'].replace("N Colorado","Northern Colorado")
ID['Team'] = ID['Team'].replace("Santa Barbara","UC Santa Barbara")
ID['Team'] = ID['Team'].replace("St Peter's","Saint Peter's")
ID['Team'] = ID['Team'].replace("Boston Univ","Boston University")
ID['Team'] = ID['Team'].replace("Alabama St","Alabama St.")
ID['Team'] = ID['Team'].replace("Sam Houston St","Sam Houston St.")
ID['Team'] = ID['Team'].replace("Morgan St","Morgan St.")
ID['Team'] = ID['Team'].replace("Ark Pine Bluff","Arkansas Pine Bluff")
ID['Team'] = ID['Team'].replace("Cleveland St","Cleveland St.")
ID['Team'] = ID['Team'].replace("Mississippi St","Mississippi St.")
ID['Team'] = ID['Team'].replace("CS Northridge","Cal St. Northridge")
ID['Team'] = ID['Team'].replace("Portland St","Portland St.")
ID['Team'] = ID['Team'].replace("Washington St","Washington St.")
ID['Team'] = ID['Team'].replace("CS Fullerton","Cal St. Fullerton")
ID['Team'] = ID['Team'].replace("Coppin St","Coppin St.")
ID['Team'] = ID['Team'].replace("S Illinois","Southern Illinois")
ID['Team'] = ID['Team'].replace("TAM C. Christi","Texas A&M; Corpus Chris")
ID['Team'] = ID['Team'].replace("Wright St","Wright St.")
ID['Team'] = ID['Team'].replace("Central Conn","Central Connecticut")
ID['Team'] = ID['Team'].replace("Jackson St","Jackson St.")
ID['Team'] = ID['Team'].replace("Florida A&M","Florida A&M;")
ID['Team'] = ID['Team'].replace("Monmouth NJ","Monmouth")
ID['Team'] = ID['Team'].replace("SE Louisiana","Southeastern Louisiana")
ID['Team'] = ID['Team'].replace("Alabama A&M","Alabama A&M;")
ID['Team'] = ID['Team'].replace("IL Chicago","Illinois Chicago")
ID['Team'] = ID['Team'].replace("UT San Antonio","UTSA")
ID['Team'] = ID['Team'].replace("C Michigan","Central Michigan")
ID['Team'] = ID['Team'].replace("Troy","Troy St.")
ID['Team'] = ID['Team'].replace("S Carolina St","South Carolina St.")
ID['Team'] = ID['Team'].replace("McNeese St","McNeese St.")
ID['Team'] = ID['Team'].replace("FL Atlantic","Florida Atlantic")
ID['Team'] = ID['Team'].replace("Alcorn St","Alcorn St.")
#missed a few later on and edited them by hand. whoops
#okay, more than a few. there was a lot all together, lets face it

In [21]:
ID.to_csv('ncaa-team-id-edited.csv')

In [169]:
team_ids = pd.read_csv('ncaa-team-id-edited.csv')
team_ids.head(10)

   Unnamed: 0  Team_ID          Team
0           0     1101   Abilene Chr
1           1     1102     Air Force
2           2     1103         Akron
3           3     1104       Alabama
4           4     1105  Alabama A&M;
5           5     1106   Alabama St.
6           6     1107        Albany
7           7     1108    Alcorn St.
8           8     1109  Alliant Intl
9           9     1110      American

In [157]:
past_results = pd.read_csv('TourneyCompactResults0216.csv')
past_results.head()

   Season  Wteam  Lteam
0    2002   1373   1108
1    2002   1104   1194
2    2002   1112   1364
3    2002   1181   1457
4    2002   1231   1428

In [170]:
winteam = []
losteam = []

for i, row in past_results.iterrows():
    for j, row2 in team_ids.iterrows():
        if row[1] == row2[1]:
            winteam.append(row2[2])
        if row[2] == row2[1]:
            losteam.append(row2[2]) 
        else:
            continue

In [171]:
year = past_results['Season'].values.tolist()   

temp_data = pd.DataFrame({'Year':year,'WinTeam':winteam,'LoseTeam':losteam})

temp_data = temp_data[['Year','WinTeam','LoseTeam']]

In [173]:
year_array = [2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016]
win = []
for i in range(0,len(year_array)):
    
    temp_teams = data.loc[data['Year'] == year_array[i]]
    temp_wl = temp_data.loc[temp_data['Year'] == year_array[i]]
    
    for j , row in temp_wl.iterrows():
        win_team = row[1]
        lose_team = row[2]
        #print win_team , lose_team
        wlogic = temp_teams['Team'] == win_team
        llogic = temp_teams['Team'] == lose_team
        wrank = temp_teams[wlogic].iloc[0].name
        lrank = temp_teams[llogic].iloc[0].name
        wdata = pd.DataFrame.as_matrix(temp_teams[wlogic])
        ldata = pd.DataFrame.as_matrix(temp_teams[llogic])

        if wdata[0,1] < ldata[0,1]:
            win.append(1)
        elif wdata[0,1] > ldata[0,1]:
            win.append(0)
        elif wdata[0,1] == ldata[0,1] and wrank < lrank:
            win.append(1)
        else:
            win.append(0)

In [174]:
tourn_win_data = pd.DataFrame({'Year':year,'WinTeam':winteam,'LoseTeam':losteam,'Win':win})
tourn_win_data = tourn_win_data[['Year','WinTeam','LoseTeam','Win']]
tourn_win_data.to_csv('tourney-results-0216.csv')

In [69]:
temp_data = pd.read_csv('data/tourney-results-0216.csv',index_col=0)
temp_data.head()

   Year  WinTeam          LoseTeam  Win
0  2002    Siena        Alcorn St.    1
1  2002  Alabama  Florida Atlantic    1
2  2002  Arizona  UC Santa Barbara    1
3  2002     Duke          Winthrop    1
4  2002  Indiana              Utah    1

In [82]:
year_array = [2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016]
for i in range(0,len(year_array)):
    temp_teams = data.loc[data['Year'] == year_array[i]]
    temp_wl = temp_data.loc[temp_data['Year'] == year_array[i]]
    for j , row in temp_wl.iterrows():
        win_team = row[1]
        lose_team = row[2]
        wlogic = temp_teams['Team'] == win_team
        llogic = temp_teams['Team'] == lose_team
        wdata = pd.DataFrame.as_matrix(temp_teams[wlogic])
        ldata = pd.DataFrame.as_matrix(temp_teams[llogic])
        difdata = wdata[0,3:]-ldata[0,3:]
        
        if j==0:
            temp_df = difdata
            print temp_df
        else:
            temp_df = np.vstack((temp_df,difdata))
        
    if i == 14:
        
        df_pandas = pd.DataFrame(temp_df, columns = ('Efficiency Margin','Offensive Efficiency',
                        'Defensive Efficiency','Tempo','Luck','Strength of Schedule',
                'Opponent Offense','Opponent Defense','Non-Conference Strength of Schedule'))
        final_data = pd.concat([temp_data,df_pandas],axis=1)

print final_data

[7.489999999999999 0.5 -7.0 -5.299999999999997 -0.16699999999999998 11.34
 5.5 -5.800000000000011 1.1400000000000001]
     Year             WinTeam              LoseTeam  Win Efficiency Margin  \
0    2002               Siena            Alcorn St.    1              7.49
1    2002             Alabama      Florida Atlantic    1             21.21
2    2002             Arizona      UC Santa Barbara    1             11.62
3    2002                Duke              Winthrop    1             39.47
4    2002             Indiana                  Utah    1             10.69
5    2002              Kansas            Holy Cross    1             29.25
6    2002            Kent St.          Oklahoma St.    0              4.68
7    2002            Kentucky            Valparaiso    1              8.55
8    2002            Missouri              Miami FL    0              1.66
9    2002          Notre Dame             Charlotte    1              3.52
10   2002            Ohio St.              Davidson    1             16.11
11   2002              Oregon               Montana    1             27.42
12   2002            Stanford      Western Kentucky    1               5.8
13   2002               Tulsa             Marquette    0             -5.83
14   2002      UNC Wilmington                   USC    0             -9.29
15   2002         Wake Forest            Pepperdine    1              5.66
16   2002             Wyoming               Gonzaga    0             -7.47
17   2002          California                  Penn    1              3.83
18   2002          Cincinnati     Boston University    1             32.94
19   2002         Connecticut               Hampton    1             15.34
20   2002           Creighton               Florida    0            -12.93
21   2002             Georgia            Murray St.    1              17.1
22   2002            Illinois         San Diego St.    1             13.87
23   2002            Maryland                 Siena    1             30.44
24   2002     Mississippi St.           McNeese St.    1             12.87
25   2002  North Carolina St.          Michigan St.    1              2.28
26   2002            Oklahoma      Illinois Chicago    1             22.14
27   2002          Pittsburgh   Central Connecticut    1             19.04
28   2002   Southern Illinois            Texas Tech    0             -3.71
29   2002               Texas        Boston College    1              7.69
..    ...                 ...                   ...  ...               ...
948  2016             Gonzaga                  Utah    0              4.06
949  2016             Indiana              Kentucky    0              -2.1
950  2016            Iowa St.  Arkansas Little Rock    1              7.72
951  2016              Kansas           Connecticut    1             10.93
952  2016            Miami FL           Wichita St.    1             -0.11
953  2016      North Carolina            Providence    1              15.3
954  2016            Virginia                Butler    1             12.35
955  2016            Maryland                Hawaii    1              8.09
956  2016          Notre Dame     Stephen F. Austin    1              0.94
957  2016            Oklahoma                   VCU    1               6.7
958  2016              Oregon        Saint Joseph's    1              7.28
959  2016            Syracuse      Middle Tennessee    1             13.85
960  2016          Texas A&M;         Northern Iowa    1             10.12
961  2016           Villanova                  Iowa    1             11.76
962  2016           Wisconsin                Xavier    0             -6.01
963  2016              Kansas              Maryland    1              9.39
964  2016            Oklahoma            Texas A&M;    1              2.52
965  2016              Oregon                  Duke    1              0.76
966  2016           Villanova              Miami FL    1              9.57
967  2016      North Carolina               Indiana    1              6.78
968  2016          Notre Dame             Wisconsin    1              0.06
969  2016            Syracuse               Gonzaga    1             -2.28
970  2016            Virginia              Iowa St.    1              8.73
971  2016            Oklahoma                Oregon    0              1.16
972  2016           Villanova                Kansas    0              2.37
973  2016      North Carolina            Notre Dame    1             13.22
974  2016            Syracuse              Virginia    0             -11.1
975  2016      North Carolina              Syracuse    1             11.24
976  2016           Villanova              Oklahoma    1              8.22
977  2016           Villanova        North Carolina    0              2.21

    Offensive Efficiency Defensive Efficiency Tempo   Luck  \
0                    0.5                   -7  -5.3 -0.167
1                   14.4                 -6.8  -2.5  0.015
2                   11.1                 -0.5   8.2  0.138
3                   23.7                -15.8   7.9 -0.066
4                    2.6                   -8   3.2  -0.06
5                   20.7                 -8.5  14.1  0.071
6                    9.1                  4.3  -1.9  -0.04
7                    2.2                 -6.4  -0.6  0.003
8                    5.9                  4.2   0.8 -0.027
9                    1.9                 -1.6   1.8 -0.079
10                    15                 -1.1   0.1 -0.138
11                  16.9                -10.5   2.8 -0.094
12                   6.3                  0.5   2.4  -0.08
13                   2.7                  8.6   4.6 -0.006
14                  -5.3                    4  -6.5  0.049
15                   7.6                  1.9  -2.1 -0.055
16                  -7.7                 -0.3  -1.1 -0.017
17                  -0.4                 -4.2   1.5  0.107
18                  16.9                  -16   2.7   -0.1
19                   2.5                -12.8   0.4  0.049
20                  -3.7                  9.2  -2.4  0.101
21                   9.9                 -7.3  -0.6 -0.038
22                   8.8                 -5.1    -1 -0.039
23                  18.6                -11.8   5.8  0.095
24                   8.2                 -4.7   0.9  0.084
25                   0.3                   -2   3.9  0.038
26                   6.1                  -16    -1  0.004
27                  11.6                 -7.4  -0.7 -0.137
28                  -5.3                 -1.7  -0.3 -0.027
29                   6.7                   -1  -0.3 -0.061
..                   ...                  ...   ...    ...
948                  0.8                 -3.2   1.6  -0.15
949                    0                  2.1   0.9  0.046
950                 11.9                  4.2   7.1 -0.118
951                  8.2                 -2.8   2.7   0.08
952                  8.1                  8.3  -0.2  0.156
953                 14.4                 -0.9   1.1 -0.118
954                  2.6                 -9.7  -6.5 -0.032
955                    8                 -0.2  -3.5  0.004
956                  8.4                  7.4  -2.9  0.047
957                  5.9                 -0.9   0.2  0.152
958                  4.8                 -2.4  -1.6   0.01
959                  8.1                 -5.8  -2.9 -0.115
960                  4.2                 -5.9   3.9 -0.006
961                  6.7                 -5.1  -2.1  0.094
962                 -7.1                 -1.1  -8.2 -0.069
963                  3.9                 -5.5   1.5  0.027
964                  4.1                  1.6   2.5  0.075
965                 -2.9                 -3.6   0.6  0.067
966                  3.4                 -6.2   0.9 -0.054
967                  2.7                 -4.1   1.4 -0.055
968                 10.5                 10.5   1.1  0.077
969                 -3.6                 -1.4  -2.3  0.011
970                 -0.6                 -9.3  -9.2  0.022
971                 -1.1                 -2.3   1.5  0.041
972                  2.7                  0.4  -2.2 -0.021
973                  3.8                 -9.4   5.1  -0.11
974                 -7.9                  3.1   3.5  0.013
975                 11.7                  0.5   4.7 -0.028
976                  4.9                 -3.3  -3.4 -0.059
977                 -1.6                 -3.8  -3.3  0.078

    Strength of Schedule Opponent Offense Opponent Defense  \
0                  11.34              5.5             -5.8
1                  15.02                6               -9
2                  14.25              8.5             -5.8
3                   20.9             12.4             -8.5
4                   7.79              4.1             -3.6
5                  17.29             10.9             -6.3
6                   -4.9             -2.2              2.7
7                   15.6              7.7             -7.8
8                   1.72              2.7              0.9
9                  -2.34             -2.2              0.2
10                  7.41              3.2             -4.2
11                 10.74              5.2             -5.6
12                 10.57              7.3             -3.2
13                 -3.47             -1.9              1.5
14                 -9.14             -6.4              2.8
15                  8.22                4             -4.2
16                  2.91                2             -0.8
17                 10.85              6.2             -4.6
18                 17.09              9.5             -7.5
19                 18.22              9.6             -8.5
20                 -8.42             -3.6              4.8
21                 12.12              5.2               -7
22                  5.47              3.3             -2.2
23                 14.22              9.2               -5
24                 14.12              7.4             -6.7
25                 -2.14             -0.2              1.9
26                  7.89              5.5             -2.4
27                 16.05              6.8             -9.3
28                 -6.05             -2.4              3.7
29                  3.54              3.7              0.1
..                   ...              ...              ...
948                -6.57             -2.7              3.9
949                -1.85              0.2              2.1
950                 14.2              6.7             -7.5
951                 6.31              3.8             -2.5
952                 8.65              7.1             -1.6
953                  2.2                2             -0.2
954                 4.37              3.5             -0.8
955                10.57              6.5             -4.2
956                17.79                9             -8.7
957                 8.75              4.1             -4.8
958                  4.6              2.1             -2.4
959                12.14                6             -6.1
960                 5.13              4.2             -0.9
961                 0.98             -0.2             -1.2
962                 1.93              2.4              0.4
963                 3.76              2.1             -1.6
964                 3.93              1.7             -2.3
965                -2.81             -3.3             -0.4
966                -1.88             -1.7              0.2
967                 4.15              2.4             -1.7
968                 0.69              0.7                0
969                 7.37              3.9             -3.4
970                 0.61              1.9              1.3
971                  3.6              2.4             -1.3
972                -2.64             -1.4              1.2
973                 0.23              0.2                0
974                 -1.9               -1              0.9
975                 0.39              0.4                0
976                -2.67             -1.4              1.3
977                -0.97             -1.4             -0.5

    Non-Conference Strength of Schedule
0                                  1.14
1                                  7.85
2                                 15.82
3                                  8.92
4                                  9.94
5                                 12.08
6                                 -0.77
7                                   8.3
8                                  3.81
9                                 -8.95
10                                   -4
11                                -1.85
12                                 4.12
13                                -1.56
14                                 1.96
15                                -2.82
16                                -7.71
17                                -3.19
18                                 7.76
19                                 5.62
20                                 0.21
21                                 0.77
22                                 6.81
23                                 6.27
24                                 -7.6
25                                -6.81
26                                 2.69
27                                -3.86
28                                -0.44
29                                 7.62
..                                  ...
948                                2.88
949                               -6.09
950                                8.02
951                                4.13
952                               -2.47
953                                 5.5
954                                7.74
955                                5.92
956                               -1.46
957                                0.18
958                               -0.27
959                                0.15
960                                0.03
961                                2.04
962                                1.14
963                                4.78
964                               -2.86
965                               -4.09
966                                0.24
967                                4.97
968                               -3.77
969                               -5.79
970                                2.29
971                                0.31
972                               -1.24
973                                3.83
974                               -4.88
975                                3.16
976                                1.64
977                                0.17

[978 rows x 13 columns]

In [83]:
final_data.to_csv('data/full-tourney-data-0216.csv',index=False)

960